### ISSUE TITLE
Automatic number formatting does not work

### ISSUE THREAD

**Issue by mountaindude** [alner/qsSimpleKPI#1]
Showing large numbers in the KPI object, e.g. 12345678, the normal Sense behaviour is to show 12.34M or similar, but the KPI object always shows 12345678. Which is a bit of a bummer..

One can of course work around it by manually formatting the number to the desired precision, but the flexibility of Auto number formatting is very nice.

Possible to fix?

**Comment by alner** [comment]
Auto number formatting feature was added. Please, download lattest release.
