### ISSUE TITLE
How to remove the "-" from KPI template ?

### ISSUE THREAD

**Issue by paulyeo11** [alner/qsSimpleKPI#10]
Hi Alex

I have post my question at Qlik View forum :-
https://community.qlik.com/thread/224096

I using your simple template for my KPI , your have 5 KPI items , i only use 3 and i need to hide the 2 KPI. i can hide all the items , except the icon up down , i unable to hide it.

Hope you can advice me.

Paul

**Comment by alner** [comment]
You need to remove it. Just remove all unnecessary expressions.

**Comment by paulyeo11** [comment]
Hi Alex

Thank you very much for your reply.

If I delete it and in case I want to add again , it is possible for me to add again ?

By the way I notice that i am not able to move the measure from last row to first row , where I go wrong ?

**Comment by alner** [comment]
You can add and move measures just as in qlik charts. The same way.

**Comment by paulyeo11** [comment]
Hi Alex

Thank you very much for your reply again 

I just try to move and still not able to move the measure , I think it is okay I just delete the last 3 measure the - Sign missing .

Just to give you feedback , this is one of the best extension I use a lot and most user friendly can help me reduce many sheet . And make my sheet very well organise , thank you very much for your good work .

Paul
