### ISSUE TITLE
when i copy your kpi with trend template to my QVF i get error msg 

### ISSUE THREAD

**Issue by paulyeo11** [alner/qsSimpleKPI#11]
Hi Alex

I post the question in forum :-1: 

https://community.qlik.com/discussion/create!input.jspa?containerType=14&containerID=2156&draftID=940927

![error kpi](https://cloud.githubusercontent.com/assets/13136214/16674570/0f786810-44ec-11e6-84f8-a55e01808b8a.png)

Hope you can advise me.

Paul

**Comment by paulyeo11** [comment]
Hi Alex

I manage to clear the error massage , what i did is i insert my expression to replace your and it work fine. 

Just like to feedback to you , you simple KPI with chart and with out chart is very useful. For example , i have a sheet in QS , with all the Ratio chart , after replace using your KPI with trend , now the whole sheet light up and make it more interesting. 

For the KPI with out adding chart , after using your i can reduce the 3 page KPI into 1 and very well organise and neat.

look like extension is very impt in QS . Only one limitation it does not support the cloud.

Paul

**Comment by alner** [comment]
Sense Cloud doens't support extensions yet. It is limitation of Qlik Cloud, not Simple KPI. 

To add or remove Master Visualizations in Simple KPI you need to use property Visualization for each measure. You need to specify object id in it. Another way just drag and drop master visualization as i stated in readme for Simple KPI. See help for master items here: [http://help.qlik.com/en-US/sense/3.0/Subsystems/Hub/Content/Assets/work-with-master-items.htm](http://help.qlik.com/en-US/sense/3.0/Subsystems/Hub/Content/Assets/work-with-master-items.htm)

**Comment by paulyeo11** [comment]
Hi Alex

Appreciate your sharing , I should have know the master items earlier . Also thank for sharing the extension not support in cloud is sense cloud issue .
