### ISSUE TITLE
Error adding 25 measures

### ISSUE THREAD

**Issue by ChristianPipe** [alner/qsSimpleKPI#14]
Hi, 

We are developing a KPIs Dashboard. We are using one object, and when we are adding the 26th measure in the object, the object "turns white".
Here are some screeshots of the error:

![image](https://cloud.githubusercontent.com/assets/21225797/17942216/da5d0bb8-6a0c-11e6-9f14-81bd3e719c97.png)

![image](https://cloud.githubusercontent.com/assets/21225797/17942182/b2ebe446-6a0c-11e6-9d12-b76201d75e1e.png)

**Comment by alner** [comment]
In my case it works... Please upload your demo app.
![image](https://cloud.githubusercontent.com/assets/5731309/17969142/4adcd734-6ad9-11e6-8479-4be11f120e23.png)
![image](https://cloud.githubusercontent.com/assets/5731309/17969193/8678d248-6ad9-11e6-85c0-728a3fc3b1b6.png)
