### ISSUE TITLE
Value Color

### ISSUE THREAD

**Issue by ChristianPipe** [alner/qsSimpleKPI#15]
Hi,

We add a dimension on our Sense App and we wanted to add a rule to paint red or gree the data .
The problem is that it does paint the data, but on the total amount of the object, and not for each dimension records.

We are adding screeshots of the problem:

![image](https://cloud.githubusercontent.com/assets/21225797/17942635/97238b22-6a0e-11e6-9a62-39efa0e4a4f5.png)

![image](https://cloud.githubusercontent.com/assets/21225797/17942654/ab2a3cec-6a0e-11e6-9d81-0e5d9d39b8af.png)

![image](https://cloud.githubusercontent.com/assets/21225797/17942687/c5a16c08-6a0e-11e6-8534-da69cc15bf26.png)

![image](https://cloud.githubusercontent.com/assets/21225797/17942701/d7259062-6a0e-11e6-8a54-381f5170c762.png)

![image](https://cloud.githubusercontent.com/assets/21225797/17942710/e372f74c-6a0e-11e6-963a-ce34c54c5948.png)

**Comment by ccamol** [comment]
Hi Alner,

**Comment by ccamol** [comment]
Hi alner, sorry for bother you again, but i want to ask you if there is way to share with me the source code of this plugin, but with the code not minified, and also what IDE do you use ?, i use WebStorm and sublime for JS. My contact is, cristian.camol@gmail.com. Thanks.

**Comment by alner** [comment]
Hi ccamol. The source code is available in the src folder. I'm using Atom editor.

**Comment by ccamol** [comment]
Alner, sure i have to bother you all day, sorry for this, but i have some questions and one have relation to this. There is a way on which i can change color on label with a condition from a field on model ?, i put some screen.

<img width="1678" alt="coloretiqueta" src="https://cloud.githubusercontent.com/assets/8439999/18063600/aa27a5de-6df9-11e6-9fad-71ad0f2ff1b6.png">

In that screen there is a css that change the color of the label, but i want to know the other way, with a condition, like function on 'background color'.

**Comment by alner** [comment]
Take a look at definition.js. You need to understand Visualization extensions API and properties definition. It is bit complicated to explain you all of my code. I'm using webpack to bundle all assets. You need to have node.js installed. Then hit npm run dev for debugging and developing... Take a look at package.json.

**Comment by jcmilhot** [comment]
Hi,

is the original issue (different color for each record of a dimension) is resolved ? (Issue from ChristianPipe)

**Comment by alner** [comment]
Please consider to use [powerkpi.rbcgrp.com](https://powerkpi.rbcgrp.com) instead. It is TED extension component.
