### ISSUE TITLE
Error adding 40 measures

### ISSUE THREAD

**Issue by ChristianPipe** [alner/qsSimpleKPI#17]
Alner, 

Hello, I have the following issue with SimpleKPI , adding a measure N° 40 , the extension does not show anything . Attached App Qlik Sense, I tried with SimpleKPI version 2.0 and 2.1 and Qlik Sense 3.0.1

Thank you.

Regards.

-> https://www.dropbox.com/s/mkdxx0c9rx74sz5/KPI_Test.zip?dl=0

**Comment by alner** [comment]
Hello, please try new build. But you have reached the current: qInitialDataFetch: [{
      qWidth: 40,
      qHeight: 250
    }
see initialProperties.js

**Comment by ChristianPipe** [comment]
Alner,

Thanks for your answer.

Regards.
