### ISSUE TITLE
Working with Internet Explorer (11)

### ISSUE THREAD

**Issue by atilleul** [alner/qsSimpleKPI#18]
Hello @alner 

I have an issue when using this nice extension for an app (located on a qs server) and opening this app on Internet Explorer (11) : (sorry errors are in French but it says the visualization is not valid because your extension (qsSimpleKPI) is not found on the server)
![ie](https://cloud.githubusercontent.com/assets/15144112/18589591/b3a94712-7c2b-11e6-986f-0be0967a48ca.jpg)

It seems it's perfectly working on Firefox (as well as Chrome) however... (so the extension has been imported without any problem)
Firefox:
![firefox](https://cloud.githubusercontent.com/assets/15144112/18589555/90756820-7c2b-11e6-8098-3e8f0427dcfc.jpg)

Do you reproduce this issue on your side (and if so could you correct it)?

Thanks!

**Comment by clark116** [comment]
I'm also having this issue! I'll post updates here if I figure it out. Anyone else?

**Comment by alner** [comment]
In my case it works. What Qlik Sense version do you use? IE version, build? OS? i've tested it in IE 11.0.9600.17843.

**Comment by atilleul** [comment]
@alner IE version is: 11.0.9600.18449 (on Windows 7) & Qlik Sense version: 2.2.3.0.

**Comment by shubhamsingh64** [comment]
@alner 
I am facing same issue with Internet Explorer 11.633.10586.0, Win 10 x64, Qlik Sense server 2.2.4.
And whatever @clark116 said is also true for me.

**Comment by shubhamsingh64** [comment]
@alner I updated the extension because I needed data handling, I had to revert back to older version due to this issue.

**Comment by alner** [comment]
Please try new build. It should fix the issue.
