### ISSUE TITLE
Link Sheet Feature Request

### ISSUE THREAD

**Issue by Dogeron** [alner/qsSimpleKPI#2]
Hi,

On the original KPI extension supplied by Qlik there was a "Link to sheet" option which allowed you to jump to another sheet - normally showing a table of the KPI source data.

![image](https://cloud.githubusercontent.com/assets/18422039/14463023/679be478-00c1-11e6-844a-42aa186f62f3.png)

Can this be added to your extension please.

Many thanks,
Dog.

**Comment by alner** [comment]
Hi, 
such functionality has already exists for each measure.

**Comment by nrwatson** [comment]
Hello Alner,

Can you explain that, please? I cant see that option under the measure,
Thanks,

**Comment by alner** [comment]
Each measure can contain link to any sheet. Which Qlik Sense version do you use? Do you use the latest version of Simple KPI object?

**Comment by nrwatson** [comment]
I use version 2.2.3, both on desktop and server. I downloaded the latest version of the extension, installed it, but I dont see a lot of the features that are described in the feature list. I'll have another look when I get a chance. Love the extension though!

**Comment by alner** [comment]
Hmmm, sounds strange... did you download qsSimpleKPI.zip file? Please try to remove old extension using QMC before install the new one
