### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by afeltmate** [alner/qsSimpleKPI#20]
I love this extension, but I can't use it in my production environment because it won't export to PDF.  Is there something that can be done so that this works?

**Comment by alner** [comment]
Yes, it is well known issues. It works in desktop, but doesn't work on server. It seems like Qlik Sense bug. Still can't solve the problem.

**Comment by alner** [comment]
It works on Qlik Sense Enterprise (3.1.x/3.2). But there is a bug exists in Qlik Printing service.  It works unstable with extensions.
