### ISSUE TITLE
Conditional Formatting for dimension

### ISSUE THREAD

**Issue by undsoul** [alner/qsSimpleKPI#21]
Is there any possibility to create conditional colour for each measures in each dimension's value ? For example, one of my customer would like to have kpi card by the drill-dimension group . There are 3 measures such as actual,target  and actual/target % . Extension aggregates calculations for each dimension's value but we couldn't achieve to show actual/target% in different colours like red and green . It gives the same colour to all dim values . 
![image](https://cloud.githubusercontent.com/assets/9967744/19763388/79bf16cc-9c46-11e6-9225-bc6181f6af8f.png)

**Comment by alner** [comment]
Nope. It doesn't available in current release.

**Comment by wbbqhs** [comment]
The extension is so awesome. Any chance this can be fixed in the next release. Currently I have to make one KPI for each value of the dimension for the conditional formatting to work.

**Comment by GiovanniLucarelli** [comment]
Hi, has anybody solved this issue?

**Comment by alner** [comment]
See powerkpi.rbcgrp.com instead.

пн, 15 апр. 2019 г., 15:08 GiovanniLucarelli notifications@github.com:
