### ISSUE TITLE
"Auto" formatting of dates

### ISSUE THREAD

**Issue by boulavogue** [alner/qsSimpleKPI#22]
Very nice tool!

I just noticed a measure of "Date(Today())" will return the number string when "Auto" is selected and not a formatted date as expected. 
Of course when "Date" is selected the formatting is correct. 

Not a major issue however this behaviour is not evident in the standard QlikSense "KPI" chart so might be relativity quick to bring it inline.

**Comment by alner** [comment]
You can remove "0A" format (just delete it)  to be able to get correct result.
