### ISSUE TITLE
Blink/Flashing in full screen when a master visualization is in the extension

### ISSUE THREAD

**Issue by jcmilhot** [alner/qsSimpleKPI#25]
The extenion is blinking/flashing in full screen when a master visualization is in it (bar chart, line chart)

**Comment by hnguyen515A** [comment]
I also have this blinking problem on small screens, too.  I hope this issue will be fixed so it can be mobile device friendly.

**Comment by alner** [comment]
Try new build please. It has been tested on Qlik Sense 3.x.
