### ISSUE TITLE
Adding qsSimpleKPI to Mashup on QS Server does not work

### ISSUE THREAD

**Issue by kuto78** [alner/qsSimpleKPI#26]
Hello,
i use qsSimple KPI on my Qlik Sense Server 3.1 SR4 standard apps and it works well.
But when I use it in a mashup, I get an error displayed "Invalid Visualisation" "The Visualisation was not found on the server". I tried to change ownership to my current user in QMC but without sucess.

Any ideas?
thanks
Tobias

**Comment by alner** [comment]
Do you build mashup using Dev Hub? It works for me in mashup on Qlik Sense Server 3.1 SR4. What do you get in chrome dev tools (Console tab, Network tab)?

**Comment by kuto78** [comment]
I build it in Dev Hub. on Chrome Console Tab I get following error:
https://qlik-web01.test.xxxx.net/qliktest/resources/assets/general/utils/drag-and-drop-service.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by alner** [comment]
It's an internal module. It's a strange behavior because on my Qlik Sense server 3.1SR4 it works in a mashup without any error. Did you change require.config somehow? Anyway, i'll look if i can do something with the problem.

**Comment by kuto78** [comment]
No changes in require.config. Many thanks for your support!

**Comment by kuto78** [comment]
We can close this issue. Deleted the old version, and updated  to newest version of qsSimpleKPI.
Mashups work now! (Sense Server 3.1 SR4)
