### ISSUE TITLE
SimpleKPI is not working on server from IE11

### ISSUE THREAD

**Issue by hamdymusleh** [alner/qsSimpleKPI#28]
Hi @alner,

I have an issue with qsSimpleKPI in IE11 in server side, it's working fine in hub from both chrome and Firefox, but it's not working from IE 11, it show me "Invalid visualization the visualization was not found on the server: qsSimpleKPI".

From localhost in desktop it's working fine with IE11, I checked it locally from both single-configuratoror and dev-hub, and it's working fine, 

Please advice why it's not working with server side?

Thanks
Hamdy

**Comment by alner** [comment]
Hi. What Qlik Sense Server version do you use?

**Comment by hamdymusleh** [comment]
Hi @alner 

We are using Qlik Sense 2.2, is it regarding to Qlik Sense version?

Thanks
Hamdy

**Comment by alner** [comment]
Please try new build.
