### ISSUE TITLE
Unable to Edit Object

### ISSUE THREAD

**Issue by banderson735** [alner/qsSimpleKPI#29]
Hi @alner and community, 

This is one of the best extensions I've ever used, so thank you!

Unfortunately, after configuring several Simple KPI objects I'm unable to go back and change any of the properties. I was able to configure a Simple KPI object with three measures and several conditional formatting properties for labels, color, and icons, but now the Simple KPI object only allows me to edit intermittently. 

Here is an example set of steps that I went through:

1. Added the Simple KPI object to my Sheet (Successful)
2. Added three measures from my master items (Successful)
3. Checked "Override parameters" to create conditional labels (Successful)
4. Tried to edit the conditional label (Unsuccessful) 

Description of 'error':  
I can edit the properties, in this case the "Label" property, but then the edits aren't implemented. If I click out of object properties or click "Done", then go back to the object, the changes I made are reverted (or gone). 

This isn't unique to the Label property, it happens with other properties. For example, the "Hide Label" property doesn't do anything when toggled. 

I'm not sure how I can troubleshoot this issue. I don't believe it's an issue with logic within any of the properties because I'm experiencing this issue when simply trying to toggle properties like "Hide Label" or changing text color. 

Any guidance on how to troubleshoot would be much appreciated because this really is one of the best extensions out there.

Thanks, 

Ben

**Comment by alner** [comment]
Hi Ben. You need to specify label enclosed with single quotes. e.g 'New Label'
