### ISSUE TITLE
Issue in Mashup referencing http://localhost:4848/resources/assets/general/utils/drag-and-drop-service.js??

### ISSUE THREAD

**Issue by BillMarkham** [alner/qsSimpleKPI#3]
Hi, I love your extension and it works great in QlikSense Desktop in a qvf.... but when embedded in a Mashup or viewed in the Single Configurator I get the message "Invalid visualization:  The visualisation was not found on the server: qsSimpleKPI".

In Chrome Dev Tools whilst referencing it with the Single Configuratorthe  get "Failed to load resource: the server  http://localhost:4848/resources/assets/general/utils/drag-and-drop-service.js??1460099147233 ".  So looks like that is what it cannot find.

I am a newbie at all this.

**Comment by alner** [comment]
Please try new [build](https://github.com/alner/qsSimpleKPI/raw/master/build/qsSimpleKPI.zip). I've fixed the bug.
