### ISSUE TITLE
Can´t import visualization to PDF or Power Point

### ISSUE THREAD

**Issue by lenninp** [alner/qsSimpleKPI#30]
Hi 
Great Job alner . I was building some KPI´s and works fine. I tried to import visualization to pdf and powr point file , but an error message appears "Invalid Visualization The visualization was not found on the server:qsSimpleKPI "

Error only appears on Qlik Sense Server versión. 
On Qlik Sense Dektop works OK

I wonder if I´m missing any setup on Qlik Sense server side

Thanks
![captura](https://cloud.githubusercontent.com/assets/26659384/24310284/f027a5a0-1094-11e7-868e-1e9adbd21e80.PNG)

**Comment by lenninp** [comment]
thanks in advance for your support

**Comment by alner** [comment]
Which Qlik Sense Enterprise version do you use? Try to restart Printing service...

**Comment by lenninp** [comment]
Hi

I restarted Printing service. but  solution did´t work. 
 Qlik Sense Enterprise versión is 3.1 SR4

Thanks for your support

**Comment by alner** [comment]
Try to open it in Chrome web browser and what kind of error do you get in dev console?

**Comment by alner** [comment]
It works fine on latest release. Qlik Sense Enterprise 3.2 SR2. Actually, on Qlik Sense 3.1 restarting printing service should solve the problem. See error logs for Printing Service.

**Comment by lenninp** [comment]
Hi
I restarted all services and now seem is working, but not at 100%
I can export visaulization to pdf and power point fromat, but i don´t know why sometimes the export works fine and sometimes not. 
When doesn´t work the error message is the same "Invalid Visualization The visualization was not found on the server:qsSimpleKPI ".

On printing service i can´t see any error . I´m ataching image that i can see on operations monitor App for Printing service
![printin_service](https://cloud.githubusercontent.com/assets/26659384/24514036/25837de2-1530-11e7-9196-eaf21abb4d4a.PNG)


Thanks again for your support

**Comment by alner** [comment]
Please see printing service log files. It doesn't show any error in qmc. Try to upgrade to 3.2 sr2 if you can.

**Comment by lenninp** [comment]
Hi 
I found this error message on System Printing CefSharp log file.


20170330T132734.226-06:00 [31] ERROR Qlik.Printing.Rendering.CefSharp.CefSharpEx.StreamResourceHandler - driver 62ed4895-c971-47ed-b62c-391b9d1f3cf8, error downloading extensions/qsSimpleKPI/qsSimpleKPI.js: Requested Service not found
20170330T133803.444-06:00 [31] ERROR Qlik.Printing.Rendering.CefSharp.CefSharpEx.StreamResourceHandler - driver 62ed4895-c971-47ed-b62c-391b9d1f3cf8, error downloading extensions/qsSimpleKPI/qsSimpleKPI.js: Requested Service not found

**Comment by alner** [comment]
Yes. The problem relates with Printing service itself. It doesn't matter wich extension visualization you use. As i said before printing service is unstable with extensions in Qlik Sense Enterprise 3.1. I had the same issue before Qlik Sense 3.2. I recommend you Upgrade to 3,2 or make support request to Qlik regariding the problem.
