### ISSUE TITLE
Can't import into Qlik Server 2.x

### ISSUE THREAD

**Issue by bruce-armstrong** [alner/qsSimpleKPI#31]
Worked fine on our 3.2 server.  However we have a 2.2 server in production after loading it there users get errors when attempting to use it (invalid visualization).

Checked the server logs and found this error on the extension load:

Error when committing.	Duplicate extension (the extension already exists or occurs more than once in the zip file): qsSimpleKPI	   at Repository.Core.Resource.Support.ExtensionResourceSupport.<>c__DisplayClass7.<CreateExtension>b__3()↵↓   at Repository.Core.Repository.Common.TransactionUtility.RunInTransaction(ITransaction transaction, IEnumerable`1 actions)	O5YIuW--ZUs2i2Cp2hX50OhfnT359ZQmfq8sHAyuJ1j3Up2Iy5kI!1923375572!NONE!1490500022206	dfc5d0cb-9717-4371-8867-9be9acdbae74

**Comment by bruce-armstrong** [comment]
Disregard the error message.  The extension works fine if I use Chrome.  Apparently it's an issue with IE11.

**Comment by bruce-armstrong** [comment]
Ok, a bit more refined information:

                                               Chrome                      Internet Explorer 11
Qlik Sense Server 2.x              works                                 fails (see below)
Qlik Sense Server 3.x              works                                 works


![image](https://cloud.githubusercontent.com/assets/6356830/24383322/20f56cac-1311-11e7-98de-5eb5113cb9f0.png)

**Comment by bruce-armstrong** [comment]
Running it through the IE debugger and it looks like it's throwing an exception here:

![image](https://cloud.githubusercontent.com/assets/6356830/24384953/1f06ce62-131c-11e7-97ea-69cbbfcfce5e.png)

A charles capture shows that it's failing right before the loading of the CSS file.

**Comment by alner** [comment]
Please try new build. It fixed.

**Comment by bruce-armstrong** [comment]
Working great now, thanks!
