### ISSUE TITLE
Auto number formatting issue in release 3.2 SR3

### ISSUE THREAD

**Issue by Bollatta** [alner/qsSimpleKPI#32]
The latest service release seams to mess with the auto number formatting for measures. For example when previous it showed 407,7K i now get 4,0,8,K using the format 0,0A. Most other configurations just leaves the number showing the total, in this case 407690.

**Comment by alner** [comment]
Corrected it. Please try the new build.

It looks like this.backendApi.localeInfo is now an empty object in QS3.2 SR3.

**Comment by Bollatta** [comment]
Perfect! Works like a charm. Excellent work!
