### ISSUE TITLE
Build Environment

### ISSUE THREAD

**Issue by aaretali** [alner/qsSimpleKPI#36]
What build environment can be used for building the extension from raw sources?

I tried in both Windows and Linux, installed node 5.3.0 on Windows and 4.2.6 on Ubiuntu, then npm installed 'gulp', 'babel' and everything else it told me it couldn't find. Ubuntu command line to build was

set NODE_ENV=production && gulp production

Windows command line:

"C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"

I had to create C:\Users\nerush directory on Windows, Linux created it in home directory with no problems.

The last error message in Windows:

[15:53:13] Starting 'build'...
Hash: 907554e9291f0bf486ed
Version: webpack 1.15.0
Time: 593ms
        Asset       Size  Chunks             Chunk Names
simple-kpi.js  293 bytes       0  [emitted]  js
chunk    {0} simple-kpi.js (js) 28 bytes [rendered]
    [0] multi js 28 bytes {0} [built] [1 error]

ERROR in Loader C:\Aare\TS\simple-kpi\node_modules\babel\index.js didn't return a function
 @ multi js
[15:53:13] Finished 'build' after 607 ms

Linux added some 70 more chunks after

[0] multi js 40 bytes {0} [built] [1 error]

'build' folder only contains qsSimpleKPI.css, simple-kpi.js (293 bytes) and simple-kpi.qext.

What am I missing?

Thanks,
Aare

**Comment by alner** [comment]
You need to have Qlik Sense desktop installed locally.  Take a look at server.config.json. Change propertis accordingly.

**Comment by alner** [comment]
...and take a look at package.json

**Comment by alner** [comment]
...and take a look at https://github.com/alner/NewQlikSenseVisualizationTemplate/blob/master/README.md
