### ISSUE TITLE
Can't Export sheet to PDF QS Server 3.2 SR4

### ISSUE THREAD

**Issue by modaloda** [alner/qsSimpleKPI#39]
Hi, I love your extension and I used to using it in my all Dashboard , but I got this issues from the users that they can't export them sheets to PDF or power point , because the Simple KPI disappear in the exported file.

Could you help us to solve this Issue , Thanks in advance

**Comment by alner** [comment]
There is a problem with Printing Service in Qlik Sense. It works ugly with extensions. I can't debug it and solve this issues as for now.

**Comment by modaloda** [comment]
Thanks for your swift response , So what we can do for Now . Should I contact with QLIK team for this issue

**Comment by alner** [comment]
Please try to restart Printing Service on the server and do the export again. If it will work you can contact Qlik support regarding unstable printing service...
