### ISSUE TITLE
Unable to use Simple KPI objects in  a mashup

### ISSUE THREAD

**Issue by nmfourga** [alner/qsSimpleKPI#4]
Hello,
I have successfully downloaded and integrated Simple KPI extension in Qlik Sense Server. However the objects I have created cannot display in Mashup. The following error is reported when dropping the object in a mashup canvas: "The visualisation is not found on the server: qsSimpleKPI".

Is there something I have missed?. Any Help?

With kind regards.

Nicodeme.

**Comment by alner** [comment]
Please try new [build](https://github.com/alner/qsSimpleKPI/blob/master/build/qsSimpleKPI.zip). I've fixed the bug.

**Comment by nmfourga** [comment]
Great !. It works.

Many thanks.
