### ISSUE TITLE
Override Parameters Label not working in Jun release with latest SimpleKPI Build

### ISSUE THREAD

**Issue by amien90** [alner/qsSimpleKPI#42]
I'm using MasterItems in SimpleKPI. These MasterItems have specific labels which makes sense in the masteritems list, but not in the frontend of SimpleKPI. I was under the assumption that i could use override parameters to give a different label in the output of SimpleKPI than the label name in the MasterItem. I now need to alter the Label in the MasterItem to show a different label in SimpleKPI. I don't really like this, because i have alot of MasterItems, and i want to use a more extensive labelname in the MasterItems list, but only a short label in the output of SimpleKPI

Is the override parameters label not working and can this be fixed, or does this feature have another purpose?

Thanks in advanced

**Comment by alner** [comment]
Please use single quotes, e.g: 'New Label'
