### ISSUE TITLE
Cannot edit qsSimpleKPI in Dev Hub

### ISSUE THREAD

**Issue by Exojolt** [alner/qsSimpleKPI#45]
Hi there!

First of, what a wonderful extension. We really use it alot in countless of apps we've published throughout our organization. 

I have a question. The company I work for requested minor style changes to this extension. I tried to edit qsSimpleKPI in the Qlik Sense Dev Hub but it keeps telling me:

> **The qsSimpleKPI is incomplete and cannot be opened or duplicated (wbfolder.wbl file missing)**

Manually creating the required wbfolder.wbl file does not solve the problem. I have contacted Qlik if this issue is caused by Qlik Sense itself. But they're persistent and they're telling me this isn't a problem from within Qlik but with the extension itself.

Is there something you could do?

I hope to hear from you soon.

Best regards,
Exo

**Comment by alner** [comment]
Hi, i'm using external editor to develop extensions. You could create any missing files manually. wbl file is required by Qlik Sense Extensions  Editor only.
