### ISSUE TITLE
Simple KPI Label Expression / Dynamic Label

### ISSUE THREAD

**Issue by dggauthier** [alner/qsSimpleKPI#46]
This question/issue is two-fold: 
1)  What function does the second field input (with the expression editor) serve? Is it a way of having a dynamic label? If so, how does it work?
![image](https://user-images.githubusercontent.com/19920595/30120046-bcb3ec22-92f5-11e7-8510-cb842732d522.png)
2) If the feature does not currently exist, would it be possible to add a feature for dynamic labeling?

**Comment by alner** [comment]
Please use single quotes, e.g: 'New Label'. Dynamic labels will be available in Qlik Sense September as a standard feature.
