### ISSUE TITLE
Increase number of items per row

### ISSUE THREAD

**Issue by sbflyboy** [alner/qsSimpleKPI#49]
Hi,
Would it be possible to increase the number of row items from 10 to 12 to be able to show 12 measures in a line to cover a full financial period. This is under measure, items per row.

Thanking in advance.
Sean Bruton

**Comment by alner** [comment]
See [powerkpi.rbcgrp.com](https://powerkpi.rbcgrp.com) instead. It is TED extension component with rich functionality.
