### ISSUE TITLE
>0 and <0 Conditionnal formatting

### ISSUE THREAD

**Issue by gib69** [alner/qsSimpleKPI#5]
Hi, 
I love this extension.
I don't find how to easily set up color to Red if negatve and Green if positive.
Is this possible ?
Otherwise it is quite complex when using calculated dimensions since claculation has to be recopied for each formatting (eg : color, icon selection...)
Thanks

**Comment by alner** [comment]
Hi,  you can use expression like this (just as example):
=if(Count(Something) > 0, '#00FF00', '#FF0000')

**Comment by gib69** [comment]
Thanks
I don't know if I missed sthing, so I rephrase my question :)
I have a long calculation used for a dimension : 

**dimension** : Gap Actual CY - BU Gross Margin Rate
**calculation** :
(
sum({$ <Actual={X},Version={'$(CurrentYearActual)'}>}[Gross Margin])
/
sum({$ <Actual={X},Version={'$(CurrentYearActual)'}>}[Net revenue])
)
-
(
sum({$ <Actual={X},Version={'$(CurrentYearBudget)'}>}[Gross Margin])
/
sum({$ <Actual={X},Version={'$(CurrentYearBudget)'}>}[Net revenue])
)

And instead of copying this in color selection and icon selection which  is heavy and risky if I change ma claculation, Il would like to use the result directly. 
Dont' know if this make things clearer, but thanks anyway for your answer
Gilles

**Comment by alner** [comment]
You can use variables for that puspose. Just define you expression in the script:

SET vKPI = 'sum({$ }[Gross Margin]) / sum({$ }[Net revenue])';

and then use macro in expressions:
$(vKPI)

**Comment by gib69** [comment]
Just Brilliant thanks
