### ISSUE TITLE
Embedded Master Visualization Issue in June 2018

### ISSUE THREAD

**Issue by davidweisheit** [alner/qsSimpleKPI#57]
In version June 2018, When I drop any master visualization over Extension SimpleKPI, this show a popup with Replace or Cancel. But I can't use a master visualization over extension. Any suggestions?

**Comment by davidweisheit** [comment]
I got the objectid from SingleConfigurator and I wrote this objectid in visualizations like a workaround.

**Comment by alner** [comment]
It works in September 2018.
