### ISSUE TITLE
Dynamic Resizing of KPI Metric Text

### ISSUE THREAD

**Issue by gearlew** [alner/qsSimpleKPI#6]
Love the KPI object! I'm using QS Desktop 2.2.4 and have experienced when I resize my window or change my resolution, even if the Dynamic resize option is selected and Auto is set for Rows, the size and the format of the KPI is not always changing. When I first created the object, it worked fine, but after some editing, color expressions, etc. the resizing of the text dynamically has stopped functioning. In addition, the format of the number was originally set to Auto but I've discovered that the formatting is not always working as expected and expands to a (in my case), a # format with two decimals [REFER to image, Item #2], and since the text does not auto resize, it truncates the values displayed [REFER to image, Item #1] in nearly all of my kpi objects. I have built separate KPI objects and all are experiencing similar behaviors.
![kpi_issue_img](https://cloud.githubusercontent.com/assets/20115415/16319054/a021e0dc-395f-11e6-967c-f93161a2a8df.jpg)

**Comment by alner** [comment]
Can you attach file with the example please?

**Comment by gearlew** [comment]
[Philanthropy vX.zip](https://github.com/alner/qsSimpleKPI/files/335088/Philanthropy.vX.zip)

**Comment by alner** [comment]
Please, try new build
