### ISSUE TITLE
Conditional Coloring Label / Conditional Icon is not working - Qlik Sense Nov 2018 

### ISSUE THREAD

**Issue by chr1111s** [alner/qsSimpleKPI#65]
Hi,

thanks for this great Extension.

I am trying to change the color from my Label and / or Icon, both statements are unfortunately not working.

I am pretty sure, my syntax is correct. Is this bug already known?

=if(Sum(Good_Quantity)>=100000,'#F93F17','#545352')

=if(Production_Line_Name='Packaging','archive icon','lab icon')

Thank you for your help. BR,

Chris

**Comment by alner** [comment]
Consider to use powerkpi.rbcgrp.com instead. It has such functionality.
