### ISSUE TITLE
Icon is not working - Qlik Sense Nov 2018

### ISSUE THREAD

**Issue by thiisme** [alner/qsSimpleKPI#69]
Good evening,
thank you for your extension, I love it!
I downloaded the version of Qlik Sense November 2018 and I can no longer insert the graphic icons near the measurement labels because the button does not work.

![icon](https://user-images.githubusercontent.com/46531973/50908794-c18dfa00-142a-11e9-9b8a-01375f0fa0bf.png)

**Comment by Mich90** [comment]
Same here.

**Comment by Tiziano93** [comment]
Hi, I have the same problem using the icons features. I solved using this words identifing the icons in the fx
https://www.w3schools.com/icons/fontawesome_icons_webapp.asp

**Comment by alner** [comment]
Please use latest build.
