### ISSUE TITLE
When KPI value -ve how to make number Color RED ?

### ISSUE THREAD

**Issue by paulyeo11** [alner/qsSimpleKPI#7]
https://community.qlik.com/thread/222497
Hi Sir

I face the above it , I post the detail issue in above link.

Paul

**Comment by alner** [comment]
Instead of =if([Sales vs Target] <0% ,'#d01919','#545352') just type the following:
=if([Sales vs Target] <0 ,'#d01919','#545352')

But it will work only if simple kpi wasn't configured to use dimension.

**Comment by paulyeo11** [comment]
[ASK.zip](https://github.com/alner/qsSimpleKPI/files/334646/ASK.zip)

Hi Alex

Thank you very much for your reply. I have follow your instruction use below :-

if([Sales vs Target] <0 ,'#d01919','#545352')

But it does not work.

Because I have Create 2 KPI

Box 1 Sales vs Target field value = 37.27%
Box 2 Sales vs Target field value = -37.27% 

I am using the same expression :-
if([Sales vs Target] <0 ,'#d01919','#545352')

Why Both box 1 & 2 display Black color word ?

Enclosed my QVF

Paul

**Comment by paulyeo11** [comment]
[ASK (2).zip](https://github.com/alner/qsSimpleKPI/files/336050/ASK.2.zip)
Hi Alex

I manage to get some help from forum to help me make it work .

https://community.qlik.com/thread/222497

But then the approach is not using macro. which mean when i try to modify the expression , i also need to modify the value color expression.

Hope you can advise me how to make the value color expression very short and sweet,

Paul

**Comment by alner** [comment]
You can use variables for storing expressions. For example, you can define variable in the script like this:

SET vKPI = 'SUM(sales)'; // simple expression just for example

Use macros in the expressions like this:

if( $(vKPI) > 0, ,'#d01919','#545352')

**Comment by paulyeo11** [comment]
[image: Inline image 1]

Hi Alex

Thank you for your reply.

Do you mean i paste  the expression :-

SET vKPI = 'SUM(sales)';

at Measure Expression Box ?

If yes , why i get the return value null ?

where I go wrong ?

Paul

**Comment by alner** [comment]
No. You need to paste the variable in the script. then you can use expression like this: if( $(vKPI) > 0, ,'#d01919','#545352')

**Comment by paulyeo11** [comment]
Hi Alex

Now working fine. Thank you very much. By the way where should i mark this case closed ?

Paul

**Comment by alner** [comment]
Hi, I've closed the issue already.

**Comment by paulyeo11** [comment]
Hi Alex

https://community.qlik.com/message/1075117#1075117

I use your simple KPI for my project , when i accidently delete one of the measure , i try to manually add new measure , the measure does not support the KPI setting. Can you share with me how to add new measure in your KPI template ?
