### ISSUE TITLE
Formatting Options

### ISSUE THREAD

**Issue by tstger** [alner/qsSimpleKPI#70]
Hello, what formatting options are possible beside 0A? 

What is the logic behind it?

I'ld like to present numbers according the Qlik Sense Standard defined in:
SET NumericalAbbreviation='3:k;6:M;9:MRD;12:T;15Smiley Tongue;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12Smiley Tongue;-15:f;-18:a;-21:z;-24:y';

**Comment by alner** [comment]
SimpleKPI doesn't support NumericalAbbreviation as for now. Consider to use [powerkpi.rbcgrp.com](powerkpi.rbcgrp.com) instead if you need such functionality.
