### ISSUE TITLE
The extension doesn't seem to work in the Dev-Hub on Qlik Sense Server 3.0

### ISSUE THREAD

**Issue by sbrusse** [alner/qsSimpleKPI#8]
In the Single Configurator the error message "visualization was not found on the server" is shown.

**Comment by BImotive** [comment]
First of all, great extension!  With regards to the limitation of 24 KPI's per object you replied:

> In the future release it will be possible to add more expressions.<

Any idea when this future is exaclty?  :-)

**Comment by alner** [comment]
> In the Single Configurator the error message "visualization was not found on the server" is shown.

I can't reproduce your problem. In my case it works.

**Comment by alner** [comment]
@BImotive > Any idea when this future is exaclty? :-)

Limitiation has been changed: 40 KPI's and 250 rows if dimension is used

**Comment by paulyeo11** [comment]
Hi All look like few of you like to have more KPI in one page , can some one share with me the usage ? Hope can paste some image here .
