### ISSUE TITLE
How to add trend chart into KPI template ?

### ISSUE THREAD

**Issue by paulyeo11** [alner/qsSimpleKPI#9]
Hi Alex 

I have create a post at Qlik view forum , and look like i am unable to get the answer :-1: 
https://community.qlik.com/thread/224112

I have read the documentation , it mentioned that i can add visualisation chart into KPI , when i try to create a visulazation chart name vSales , and when i paste the vSales into the visulization box , but it does work.

Hope you can help me.

Paul

**Comment by alner** [comment]
You can add measure with some fake value (for example, using the following expression: ='Drag and Drop here'), then drag and drop **master visualization** into the value region or you can insert object id into the "Visualization" property for each measure.

**Comment by paulyeo11** [comment]
Hi Alex

Thank you vey much it work fine now. when i try to create a new measure and manage to move my visulisation chart into to text box.  many thank again.
